- set_fact:
    apache_installed: false
    nginx_installed: false
- include: manager/main.yml
- include: user.yml
- include: gitdeploy.yml
- include: monit.yml
- include: apache/main.yml
- include: nginx/main.yml
- fail: msg="This scripts supports only Apache and nginx and one of them must be installed on the target server"
  when: apache_installed != True and nginx_installed != True
- name: Your deploy key
  debug: msg="{{ ''.join(ssh_pubkey.stdout_lines) }}"
- name: Your webhook
  debug: msg="http://gitdeploy:{{ gitdeploy_password }}@{{ ansible_default_ipv4.address }}/_autodeploy"
