- name: Install git
  apt: pkg=git state=latest
- name: Install monit
  apt: pkg=monit state=latest
- name: Install pwgen
  apt: pkg=pwgen state=latest
- name: Install apache2-utils
  apt: pkg=apache2-utils state=latest
